### PR TITLE
docs(using-nvm): added NVM guide

### PR DESCRIPTION
**Pull request by danielsogl**

### CODE REVIEW

**Comment by piotrowski** [comment]
Meh, review was pending - so too late now. Fixed in #1149

**Comment by danielsogl** [comment]
@piotrowski thank you for pointing me out. I forgot to update my PR. I will fix that!

**Comment by piotrowski** [comment]
Nah, it's already merged and I made a PR with the 3 typo fixes but also additional stuff at #1149

**Comment by danielsogl** [comment]
@piotrowski I see. Thank you!

**Pull request merged**
