### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by tonyawad88**
Fixes ionic cordova build command, which no longer requires --release at the end of it.

### CODE REVIEW

**Comment by perrygovier** [comment]
@mhartington, this true?

**Comment by mhartington** [comment]
This is indeed, false.

**Comment by tonyawad88** [comment]
@mhartington what is the difference? The same steps are executed when invoking both.
```
ionic cordova build --prod
```
```
[18:12:46]  build prod started ... 
[18:12:46]  clean started ... 
[18:12:46]  clean finished in 7 ms 
[18:12:46]  copy started ... 
[18:12:46]  deeplinks started ... 
[18:12:47]  deeplinks finished in 28 ms 
[18:12:47]  ngc started ... 
[18:12:54]  ngc finished in 7.17 s 
[18:12:54]  preprocess started ... 
[18:12:54]  preprocess finished in 1 ms 
[18:12:54]  webpack started ... 
[18:12:54]  copy finished in 7.64 s 
[18:13:24]  webpack finished in 30.48 s 
[18:13:24]  uglify started ... 
[18:13:24]  sass started ... 
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
[18:13:26]  sass finished in 1.50 s 
[18:13:26]  cleancss started ... 
[18:13:28]  cleancss finished in 2.18 s 
[18:13:37]  uglify finished in 12.64 s 
[18:13:37]  postprocess started ... 
[18:13:37]  postprocess finished in 19 ms 
[18:13:37]  lint started ... 
[18:13:37]  build prod finished in 50.47 s 
> cordova build android
```
```
ionic cordova build --prod --release
```
```
[18:14:16]  build prod started ... 
[18:14:16]  clean started ... 
[18:14:16]  clean finished in 3 ms 
[18:14:16]  copy started ... 
[18:14:16]  deeplinks started ... 
[18:14:16]  deeplinks finished in 30 ms 
[18:14:16]  ngc started ... 
[18:14:24]  ngc finished in 7.96 s 
[18:14:24]  preprocess started ... 
[18:14:24]  preprocess finished in less than 1 ms 
[18:14:24]  webpack started ... 
[18:14:25]  copy finished in 8.44 s 
[18:14:55]  webpack finished in 30.55 s 
[18:14:55]  uglify started ... 
[18:14:55]  sass started ... 
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
[18:14:57]  sass finished in 1.91 s 
[18:14:57]  cleancss started ... 
[18:14:59]  cleancss finished in 2.27 s 
[18:15:09]  uglify finished in 14.34 s 
[18:15:09]  postprocess started ... 
[18:15:09]  postprocess finished in 21 ms 
[18:15:09]  lint started ... 
[18:15:09]  build prod finished in 53.04 s 
> cordova build android --release
```

**Comment by mhartington** [comment]
The `--release` flag is part of the cordova build process, not Ionics.

**Pull request closed without merging**
