### PR TITLE
Updated Docs with generated code

### PR DESCRIPTION
**Pull request by marcorieser**

### CODE REVIEW

**Comment by piotrowski** [comment]
Could you explain a bit what exactly you changed and why you?

**Comment by marcorieser** [comment]
Because i generated the tutorial project with the cli and the generated code was not like the docs (https://ionicframework.com/docs//intro/tutorial/project-structure/) so i changed the docs to be the same like the generated code. By the way on the next page (https://ionicframework.com/docs//intro/tutorial/adding-pages/) the ion-nav already has the reference to #content like i changed it.

**Comment by joaquintoral** [comment]
@marcorieser, @janpio same thing for the getting started page. The generated code do not match the codes written in the getting started part of the documentation and so on.

**Comment by janpio** [comment]
@joaquintoral Feel free to submit a PR changing that yourself.

**Comment by haxwell** [comment]
This change was originally made in #1091, but over time that came to be in a conflict state. It is now addressed in PR #1383. Once 1383 is committed, both this issue and 1091 should be closed.

**Comment by haxwell** [comment]
@mhartington FYI, this should be closed. #1383 addressed this change.

**Pull request closed without merging**
