### PR TITLE
docs(native): tweaks to structure and content

### PR DESCRIPTION
**Pull request by janpio**
Adds an additional headline "What Ionic Native offers" for the feature headlines "Promises and Observables" and " Runtime Diagnostics". 
Adds an additional paragraph for "Native Plugins in the Browser" that surfaces the Browser Usage subpage.
Several smaller text tweaks in wording and for completeness.
New paragraph "Use plugin functionality in your app" as last step of "Usage"

### CODE REVIEW

**Comment by piotrowski** [comment]
Anything blocking a merge of this?

**Comment by danielsogl** [comment]
@piotrowski you should fix some conflicts

**Comment by piotrowski** [comment]
Done. Strange that this conflicted... shouldn't have.

I still think these would be great changes.

**Comment by janpio** [comment]
1 month bump... Stil lthink this would be really useful.

**Pull request closed without merging**
