### PR TITLE
Updated info following the tutorial

### PR DESCRIPTION
**Pull request by edinhojorge**
Added updated info following the tutorial as some differences was found between tutorial and practice.
- Updated template list
- Select template info
- Link with ionic account

### CODE REVIEW

**Comment by anthony-curtis** [comment]
Thanks for creating this pull request. I was about to make similar recommendations.

Might I suggest changing this sentence:

> Just accept next steps in CLI. You will be asked to link it with your account, but you don't need to  at this moment if you don't want to (select nevermind).

To something like this:

> During setup the CLI may ask if you want to integrate your new app with Cordova or install the free Ionic Pro SDK. For this tutorial you can choose "no."

**Comment by edinhojorge** [comment]
Sure, done!

**Comment by mhartington** [comment]
Hey thanks for the PR! Can you fix the conflict and then we can merge?

**Comment by edinhojorge** [comment]
Fixed. I ran all steps again.

**Pull request closed without merging**
